trigger:
- master

variables:
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  vmImageName: 'windows-latest'
  azureSubscription: 'Red Folder Production (20366cfc-092d-46d6-a630-a687d3a04992)'

stages:
- stage: Build
  displayName: 'Test, Build & Publish'

  jobs:
    - job: Build
      displayName: 'Test, Build & Publish'
      pool:
        vmImage: $(vmImageName)

      steps:
        - task: UseDotNet@2
          displayName: 'Use .NET Core sdk'
          inputs:
            packageType: sdk
            version: 2.x

        - task: DotNetCoreCLI@2
          displayName: Restore
          inputs:
            command: 'restore'
            projects: '**/*.csproj'

        - task: DotNetCoreCLI@2
          displayName: Build
          inputs:
            command: 'build'
            projects: '**/*.csproj'
            arguments: '--configuration $(BuildConfiguration)'

        - task: DotNetCoreCLI@2
          displayName: 'Test: Red-Folder.Blog.Markdown.Tests.Unit'
          inputs:
            command: test
            projects: 'tests/Red-Folder.Blog.Markdown.Tests.Unit/Red-Folder.Blog.Markdown.Tests.Unit.csproj'

        - task: DotNetCoreCLI@2
          displayName: 'Publish: Red-Folder.com'
          inputs:
            command: publish
            publishWebProjects: false
            projects: src/Red-Folder.com/Red-Folder.com.csproj
            arguments: '--configuration $(BuildConfiguration) --output $(Build.ArtifactStagingDirectory)/website'

        - publish: $(Build.ArtifactStagingDirectory)/website
          displayName: 'Publish Website'
          artifact: website

        - task: DotNetCoreCLI@2
          displayName: 'Publish: Acceptance Tests'
          inputs:
            command: publish
            publishWebProjects: false
            projects: tests/Red-Folder.Tests.Acceptance/Red-Folder.Tests.Acceptance.csproj
            arguments: '--configuration $(BuildConfiguration) --output $(Build.ArtifactStagingDirectory)/acceptance_tests'

        - publish: $(Build.ArtifactStagingDirectory)/acceptance_tests
          displayName: 'Publish Acceptance Tests'
          artifact: acceptance_tests

- stage: DeployToStaging
  displayName: 'Deploy To Staging'
  dependsOn: Build
  condition: succeeded()
  jobs:
    - deployment: Deploy
      displayName: 'Deploy To Staging'
      environment: 'staging'
      pool:
        vmImage: $(vmImageName)

      strategy:
        runOnce:
          deploy:
            steps:
            - task: AzureRmWebAppDeployment@3
              displayName: 'Deploy to Staging'
              inputs:
                azureSubscription: '$(azureSubscription)'
                appType: app
                WebAppName: 'RFC-Website-Staging'
                Package: '$(Pipeline.Workspace)/website/Red-Folder.com.zip'
                TakeAppOfflineFlag: true

- stage: VerifyStaging
  displayName: 'Verify Staging'
  dependsOn: DeployToStaging
  condition: succeeded()
  jobs:
    - deployment: Verify
      displayName: 'VerifyStaging'
      environment: 'staging'
      pool:
        vmImage: $(vmImageName)

      strategy:
        runOnce:
          deploy:
            steps:
            - task: UseDotNet@2
              displayName: 'Use .NET Core sdk'
              inputs:
                packageType: sdk
                version: 2.x

            - task: jessehouwing.jessehouwing-vsts-variable-tasks.vsts-variable-set.VariableSetTask@1
              displayName: 'Set variable: Red-Folder.Tests.Acceptance.Host'
              inputs:
                VariableName: 'Red-Folder.Tests.Acceptance.Host'
                Value: '$(Red-Folder.Test.Acceptance.Host)'
            - task: jessehouwing.jessehouwing-vsts-variable-tasks.vsts-variable-set.VariableSetTask@1
              displayName: 'Set variable: Red-Folder.Tests.Acceptance.Host_Synonyms'
              inputs:
                VariableName: 'Red-Folder.Tests.Acceptance.Host_Synonyms'
                Value: '$(Red-Folder.Test.Acceptance.Host_Synonyms)'
            - task: jessehouwing.jessehouwing-vsts-variable-tasks.vsts-variable-set.VariableSetTask@1
              displayName: 'Set variable: Red-Folder_Tests_Acceptance_CrawlWrapper_StartKey'
              inputs:
                VariableName: 'Red-Folder_Tests_Acceptance_CrawlWrapper_StartKey'
                Value: '$(Red-Folder_Tests_Acceptance_CrawlWrapper_StartKey)' 
      
            - task: ExtractFiles@1
              displayName: 'Extract files '
              inputs:
                archiveFilePatterns: '$(Pipeline.Workspace)/acceptance_tests/Red-Folder.Tests.Acceptance.zip'
                destinationFolder: '$(System.DefaultWorkingDirectory)/Red-Folder.Tests.Acceptance'

            - task: VSTest@2
              displayName: 'Run Acceptance Tests'
              inputs:
                testAssemblyVer2: '**\Red-Folder.Tests.Acceptance.dll'
                searchFolder: '$(System.DefaultWorkingDirectory)/Red-Folder.Tests.Acceptance'
                otherConsoleOptions: '/Framework:".NETCoreApp,Version=v2.0"'
                diagnosticsEnabled: True        