parameters:
  - name: stageName
    type: string
    
  - name: vmImageName
    type: string

stages:
- stage: Verify${{ parameters.stageName }}
  displayName: 'Verify ${{ parameters.stageName }}'
  variables:
    - group: 'Red-Folder-WebCrawl-${{ parameters.stageName }}'
  jobs:
    - deployment: Verify
      displayName: 'Verify ${{ parameters.stageName }}'
      environment: ${{ parameters.stageName }}
      pool:
        vmImage: ${{ parameters.vmImageName }}

      strategy:
        runOnce:
          deploy:
            steps:
            - task: UseDotNet@2
              displayName: 'Use .NET Core sdk'
              inputs:
                packageType: sdk
                version: 2.x

            - task: ExtractFiles@1
              displayName: 'Extract files '
              inputs:
                archiveFilePatterns: '$(Pipeline.Workspace)/acceptance_tests/Red-Folder.Tests.Acceptance.zip'
                destinationFolder: '$(System.DefaultWorkingDirectory)/Red-Folder.Tests.Acceptance'

            - task: VSTest@2
              displayName: 'Run Acceptance Tests'
              inputs:
                testAssemblyVer2: '**\Red-Folder.Tests.Acceptance.dll'
                searchFolder: '$(System.DefaultWorkingDirectory)/Red-Folder.Tests.Acceptance'
                otherConsoleOptions: '/Framework:".NETCoreApp,Version=v2.0"'
                diagnosticsEnabled: True
              env:
                Red-Folder_Tests_Acceptance_CrawlWrapper_StartKey: $(AcceptanceTest.StartKey)
                Red-Folder_Tests_Acceptance_Host: $(AcceptanceTest.Host)
                Red-Folder_Tests_Acceptance_Host_Synonyms: $(AcceptanceTest.Host_Synonyms)     
