trigger:
- master

variables:
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  vmImageName: 'windows-latest'

stages:
- stage: Build
  displayName: 'Test, Build & Publish'

  jobs:
    - job: Build
      displayName: 'Test, Build & Publish'
      pool:
        vmImage: $(vmImageName)

      steps:
        - task: UseDotNet@2
          displayName: 'Use .NET Core sdk'
          inputs:
            packageType: sdk
            version: 2.0

        - task: DotNetCoreCLI@2
          displayName: Restore
          inputs:
            command: 'restore'
            projects: '**/*.csproj'

        - task: DotNetCoreCLI@2
          displayName: Build
          inputs:
            command: 'build'
            projects: '**/*.csproj'
            arguments: '--configuration $(BuildConfiguration)'

        - task: DotNetCoreCLI@2
          displayName: 'Test: Red-Folder.Blog.Markdown.Tests.Unit'
          inputs:
            command: test
            projects: 'tests/Red-Folder.Blog.Markdown.Tests.Unit/Red-Folder.Blog.Markdown.Tests.Unit.csproj'

        - task: DotNetCoreCLI@2
          displayName: 'Publish: Red-Folder.com'
          inputs:
            command: publish
            publishWebProjects: false
            projects: src/Red-Folder.com/Red-Folder.com.csproj
            arguments: '--configuration $(BuildConfiguration) --output $(Build.ArtifactStagingDirectory)/website'

        - publish: $(Build.ArtifactStagingDirectory)/website
          displayName: 'Publish Website'
          artifact: website

        - task: DotNetCoreCLI@2
          displayName: 'Publish: Acceptance Tests'
          inputs:
            command: publish
            publishWebProjects: false
            projects: tests/Red-Folder.Tests.Acceptance/Red-Folder.Tests.Acceptance.csproj
            arguments: '--configuration $(BuildConfiguration) --output $(Build.ArtifactStagingDirectory)/acceptance_tests'

        - publish: $(Build.ArtifactStagingDirectory)/acceptance_tests
          displayName: 'Publish Acceptance Tests'
          artifact: acceptance_tests

